<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'

type Status = '正常' | '停用'
type QuestionType = '单选' | '多选' | '单行文本' | '多行文本'
interface Question { id: string; title: string; category: string; type: QuestionType; status: Status; options: string[] }
interface QuestionBank { id: string; version: string; name: string; description: string; questionIds: string[]; status: Status }

const props = defineProps<{ mode: 'bank' | 'question' }>()
const categories = ['睡眠评估', '生活方式', '营养状况', '健康诉求'] // 来源：系统设置 / 参数管理 / 题目分类
const questions = ref<Question[]>([
  { id: 'Q-0001', title: '近期睡眠质量', category: '睡眠评估', type: '单选', status: '正常', options: ['良好', '一般', '较差'] },
  { id: 'Q-0002', title: '日间能量水平', category: '生活方式', type: '单选', status: '正常', options: ['充沛', '一般', '偏低'] },
  { id: 'Q-0003', title: '运动频率', category: '生活方式', type: '单选', status: '正常', options: ['每周 3 次及以上', '每周 1-2 次', '很少运动'] },
  { id: 'Q-0004', title: '主要健康诉求', category: '健康诉求', type: '多行文本', status: '正常', options: [] },
])
const banks = ref<QuestionBank[]>([
  { id: 'QB-0001', version: 'V1.0', name: '基础健康测评题库', description: '适用于首次到店顾客的基础健康评估。', questionIds: ['Q-0001', 'Q-0002', 'Q-0003'], status: '正常' },
  { id: 'QB-0002', version: 'V1.1', name: '睡眠与精力专项题库', description: '用于睡眠、精力与营养专项测评。', questionIds: ['Q-0001', 'Q-0002', 'Q-0004'], status: '停用' },
])
const keyword = ref(''); const statusFilter = ref(''); const categoryFilter = ref(''); const typeFilter = ref('')
const bankModal = ref(false); const questionModal = ref(false); const bankEditing = ref(false); const questionEditing = ref(false)
const blankBank = (): QuestionBank => ({ id: '', version: '', name: '', description: '', questionIds: [], status: '正常' })
const blankQuestion = (): Question => ({ id: '', title: '', category: '', type: '单选', status: '正常', options: [''] })
const bankDraft = ref<QuestionBank>(blankBank()); const questionDraft = ref<Question>(blankQuestion())
const filteredBanks = computed(() => banks.value.filter(item => (!keyword.value || `${item.version}${item.name}`.includes(keyword.value)) && (!statusFilter.value || item.status === statusFilter.value)))
const filteredQuestions = computed(() => questions.value.filter(item => (!keyword.value || item.title.includes(keyword.value)) && (!categoryFilter.value || item.category === categoryFilter.value) && (!typeFilter.value || item.type === typeFilter.value) && (!statusFilter.value || item.status === statusFilter.value)))
function openBank(item?: QuestionBank) { bankEditing.value=!!item; bankDraft.value=item ? { ...item, questionIds:[...item.questionIds] } : blankBank(); bankModal.value=true }
function openQuestion(item?: Question) { questionEditing.value=!!item; questionDraft.value=item ? { ...item, options:[...item.options] } : blankQuestion(); questionModal.value=true }
function saveBank() { const item=bankDraft.value; item.questionIds=item.questionIds.filter(Boolean); if(!item.version.trim() || !item.name.trim() || !item.description.trim() || !item.questionIds.length) return alert('请完成题库版本、名称、说明及测评题目'); if(new Set(item.questionIds).size !== item.questionIds.length) return alert('同一题目不可重复添加'); if(bankEditing.value){ const index=banks.value.findIndex(x=>x.id===item.id); banks.value.splice(index,1,{...item,questionIds:[...item.questionIds]}) } else banks.value.unshift({...item,id:`QB-${String(Date.now()).slice(-6)}`,questionIds:[...item.questionIds]}); bankModal.value=false }
function saveQuestion() { const item=questionDraft.value; const requiresOptions=['单选','多选'].includes(item.type); if(!item.title.trim() || !item.category || (requiresOptions && !item.options.filter(Boolean).length)) return alert('请完成题目标题、所属分类和选项值'); const saved={...item,options:requiresOptions ? item.options.filter(Boolean) : []}; if(questionEditing.value){ const index=questions.value.findIndex(x=>x.id===item.id); questions.value.splice(index,1,saved) } else questions.value.unshift({...saved,id:`Q-${String(Date.now()).slice(-6)}`}); questionModal.value=false }
function toggleStatus(item: { status: Status }) { item.status=item.status==='正常'?'停用':'正常' }
function removeBank(item: QuestionBank) { if(item.status!=='停用') return alert('仅停用状态的题库允许删除'); if(confirm(`确认删除题库“${item.name}”吗？`)) banks.value=banks.value.filter(x=>x.id!==item.id) }
function removeQuestion(item: Question) { if(item.status!=='停用') return alert('仅停用状态的题目允许删除'); if(confirm(`确认删除题目“${item.title}”吗？`)) { questions.value=questions.value.filter(x=>x.id!==item.id); banks.value.forEach(bank=>bank.questionIds=bank.questionIds.filter(id=>id!==item.id)) } }
function addOption(){ questionDraft.value.options.push('') }
function removeOption(index:number){ questionDraft.value.options.splice(index,1) }
function addQuestionRow(){ bankDraft.value.questionIds.push('') }
function removeQuestionRow(index:number){ bankDraft.value.questionIds.splice(index,1) }
function questionAlreadySelected(questionId: string, rowIndex: number){ return bankDraft.value.questionIds.some((selected, index) => index !== rowIndex && selected === questionId) }
function closeOverlayFromMask(event: MouseEvent){ if((event.target as HTMLElement).classList.contains('overlay')) { bankModal.value=false; questionModal.value=false } }
onMounted(() => document.addEventListener('click', closeOverlayFromMask))
onUnmounted(() => document.removeEventListener('click', closeOverlayFromMask))
</script>

<template>
  <template v-if="mode==='bank'">
    <div class="toolbar"><input v-model="keyword" placeholder="查询题库版本、题库名称"/><select v-model="statusFilter"><option value="">全部状态</option><option>正常</option><option>停用</option></select><button class="primary" @click="openBank()">+ 新增题库</button></div>
    <section class="panel table-panel"><h3>题库管理 <small>测评题目来自题目管理；题目分类由系统设置 / 参数管理维护。</small></h3><table><thead><tr><th>题库编号</th><th>题库版本</th><th>题库名称</th><th>题库说明</th><th>测评题目数量</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in filteredBanks" :key="item.id"><td>{{item.id}}</td><td>{{item.version}}</td><td><b>{{item.name}}</b></td><td>{{item.description}}</td><td>{{item.questionIds.length}}</td><td><span :class="['tag',item.status==='正常'?'已生效':'待补资料']">{{item.status}}</span></td><td class="actions"><button @click="openBank(item)">编辑</button><button class="link" @click="toggleStatus(item)">{{item.status==='正常'?'停用':'启用'}}</button><button v-if="item.status==='停用'" class="link danger" @click="removeBank(item)">删除</button></td></tr><tr v-if="!filteredBanks.length"><td colspan="7" class="empty">暂无符合条件的题库</td></tr></tbody></table></section>
    <div v-if="bankModal" class="overlay"><div class="dialog"><button class="close" @click="bankModal=false">×</button><h2>{{bankEditing?'编辑题库':'新增题库'}}</h2><label>题库版本 <b>*</b><input v-model="bankDraft.version" placeholder="例如 V1.2"/></label><label>题库名称 <b>*</b><input v-model="bankDraft.name" placeholder="请输入题库名称"/></label><label>题库说明 <b>*</b><textarea v-model="bankDraft.description" rows="3" placeholder="请输入题库说明"></textarea></label><section class="bank-questions"><div class="bank-questions-head"><span>测评题目 <b>*</b></span><button type="button" @click="addQuestionRow">+ 添加题目</button></div><div v-for="(_,index) in bankDraft.questionIds" :key="index" class="bank-question-row"><span>{{index + 1}}</span><select v-model="bankDraft.questionIds[index]"><option value="">请选择已有题目</option><option v-for="question in questions.filter(item=>item.status==='正常')" :key="question.id" :value="question.id" :disabled="questionAlreadySelected(question.id,index)">{{question.title}} · {{question.category}} · {{question.type}}</option></select><button type="button" class="link danger" @click="removeQuestionRow(index)">删除</button></div><p v-if="!bankDraft.questionIds.length">请点击“添加题目”，从题目管理列表选择已有题目。</p></section><footer><button @click="bankModal=false">取消</button><button class="primary" @click="saveBank">保存</button></footer></div></div>
  </template>
  <template v-else>
    <div class="toolbar question-toolbar"><input v-model="keyword" placeholder="查询题目标题"/><select v-model="categoryFilter"><option value="">全部分类</option><option v-for="item in categories" :key="item">{{item}}</option></select><select v-model="typeFilter"><option value="">全部题目类型</option><option>单选</option><option>多选</option><option>单行文本</option><option>多行文本</option></select><select v-model="statusFilter"><option value="">全部状态</option><option>正常</option><option>停用</option></select><button class="primary" @click="openQuestion()">+ 新增题目</button></div>
    <section class="panel table-panel"><h3>题目管理 <small>所属分类调用系统设置 / 参数管理中的题目分类参数。</small></h3><table><thead><tr><th>题目编号</th><th>题目标题</th><th>所属分类</th><th>题目类型</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in filteredQuestions" :key="item.id"><td>{{item.id}}</td><td><b>{{item.title}}</b><br><small v-if="item.options.length">选项：{{item.options.join('、')}}</small></td><td>{{item.category}}</td><td>{{item.type}}</td><td><span :class="['tag',item.status==='正常'?'已生效':'待补资料']">{{item.status}}</span></td><td class="actions"><button @click="openQuestion(item)">编辑</button><button class="link" @click="toggleStatus(item)">{{item.status==='正常'?'停用':'启用'}}</button><button v-if="item.status==='停用'" class="link danger" @click="removeQuestion(item)">删除</button></td></tr><tr v-if="!filteredQuestions.length"><td colspan="6" class="empty">暂无符合条件的题目</td></tr></tbody></table></section>
    <div v-if="questionModal" class="overlay"><div class="dialog"><button class="close" @click="questionModal=false">×</button><h2>{{questionEditing?'编辑题目':'新增题目'}}</h2><label>题目标题 <b>*</b><input v-model="questionDraft.title" placeholder="请输入题目标题"/></label><label>所属分类 <b>*</b><select v-model="questionDraft.category"><option value="">请选择题目分类</option><option v-for="item in categories" :key="item">{{item}}</option></select></label><label>题目类型 <b>*</b><select v-model="questionDraft.type"><option>单选</option><option>多选</option><option>单行文本</option><option>多行文本</option></select></label><label>状态<select v-model="questionDraft.status"><option>正常</option><option>停用</option></select></label><template v-if="['单选','多选'].includes(questionDraft.type)"><label>选项值 <b>*</b><div class="option-list"><div v-for="(_,index) in questionDraft.options" :key="index"><input v-model="questionDraft.options[index]" :placeholder="`选项 ${index+1}`"/><button type="button" class="link danger" @click="removeOption(index)">删除</button></div><button type="button" @click="addOption">+ 添加选项</button></div></label></template><footer><button @click="questionModal=false">取消</button><button class="primary" @click="saveQuestion">保存</button></footer></div></div>
  </template>
</template>

<style scoped>
.actions{white-space:nowrap}.danger{color:#a4423b;background:#ffeceb}.empty{text-align:center;padding:24px;color:#778096}.question-toolbar{flex-wrap:wrap}.overlay{position:fixed;inset:0;z-index:50;display:grid;place-items:center;background:rgba(20,25,36,.38)}.dialog{position:relative;width:min(800px,92vw);height:min(720px,90vh);max-height:none;overflow:auto;padding:0;border-radius:14px;background:#fff}.dialog h2{position:sticky;top:0;z-index:3;margin:0;padding:22px 58px 18px 25px;border-bottom:1px solid #edf0f4;background:#fff}.dialog label{display:block;margin:13px 25px;font-size:12px;color:#586174}.dialog label>b,.bank-questions b{color:#b24b42}.dialog input,.dialog select,.dialog textarea{display:block;width:100%;margin-top:7px;padding:9px 11px;border:1px solid #dce0e8;border-radius:8px;background:#fff}.dialog footer{position:sticky;bottom:0;z-index:3;display:flex;justify-content:flex-end;gap:9px;margin:18px 0 0;padding:14px 25px;border-top:1px solid #edf0f4;background:#fff}.close{position:sticky;top:16px;z-index:4;float:right;margin:16px 18px -48px 0;border-radius:50%;font-size:19px;width:32px;height:32px;padding:0}.bank-questions{margin:15px 25px}.bank-questions-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;font-size:12px;color:#586174}.bank-questions-head button{padding:6px 9px}.bank-question-row{display:flex;align-items:center;gap:8px;margin-bottom:7px}.bank-question-row>span{display:grid;place-items:center;width:24px;height:24px;border-radius:50%;background:#f1f3f7;color:#778096;font-size:11px}.bank-question-row select{flex:1;margin:0}.bank-question-row button{flex:0 0 auto}.bank-questions>p{margin:0;padding:14px;border:1px dashed #dce0e8;border-radius:8px;color:#778096;font-size:12px}.option-list{display:grid;gap:7px;margin-top:7px}.option-list>div{display:flex;gap:8px}.option-list input{margin:0}.option-list button{align-self:center}.option-list>button{justify-self:start}
</style>
